apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pitreos
spec:
  serviceName: pitreos
  selector:
    matchLabels:
      app: pitreos
  replicas: 1
  template:
    metadata:
      labels:
        app: pitreos
    spec:
      containers:
      - name: pitreos
        image: gcr.io/eoscanada-shared-services/pitreos:latest
        command:
        - /bin/sleep
        args:
        - "10600"
        volumeMounts:
        - mountPath: /pitreos
          name: pitreosssd
  volumeClaimTemplates:
  - metadata:
      name: pitreosssd
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: gcpssd
      resources:
        requests:
          storage: 100Gi
